#!/bin/bash
command -v mpv >/dev/null 2>&1 || { echo >&2 "mpv required but not installed"; exit 1; }

m3u=$1

config_path="$HOME/.config/iptv/"
channels_file="$config_path/channels"
m3u_url_file="$config_path/m3u_url"
tmp_playlist="$config_path/iptvplaylist"
player_pid_file="/tmp/iptvplayerpid"

mkdir -p "$config_path"

usage() {
  cat <<EOF
usage: iptv [M3U_URL]

    [M3U_URL]    URL to a M3U playlist, required on first run
    --help       Display help
EOF
}

save_channels() {
  m3u_url=$(cat "$m3u_url_file")

  printf "\nLoading channels... "
  curl -s "$m3u_url" | grep EXTINF: -A 2 > $tmp_playlist
  printf "Done!\n"

  printf "Parsing channels... "
  channels=()
  url=""

  while IFS= read -r line; do
  if [[ "$line" =~ tvg-name=\"([^\"]+)\" || "$line" =~ tvg-id=\"([^\"]+)\" ]]; then
    name="${BASH_REMATCH[1]}"
    url=""
  elif [[ "$line" == http* ]]; then
    url="$line"
    channels+=("$name [CH:${#channels[@]}] url:$url")
  fi
  done < "$tmp_playlist"

  printf "Done!\n"

  printf "%s\n" "${channels[@]}" > $channels_file
}

if [ -z "$m3u" ] && [ ! -s "$channels_file" ]; then
  usage
  exit 1
fi

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
  usage
  exit 0
fi

if [ ! -z "$m3u" ]; then
  echo "$m3u" > $m3u_url_file
  save_channels

  echo "Playlist saved. Now run iptv again without a M3U URL."
  exit
fi

if [[ $(find "$channels_file" -mtime +1) ]]; then
  printf "Doing a daily update of channels..\n"
  save_channels
fi
