#!/bin/bash
command -v mpv >/dev/null 2>&1 || { echo >&2 "mpv required but not installed"; exit 1; }

config_path="$HOME/.config/iptv/"
channels_file="$config_path/channels"
m3u_url_file="$config_path/m3u_url"
tmp_playlist="/tmp/iptvplaylist"
player_pid_file="/tmp/iptvplayerpid"

mkdir -p "$config_path"

usage() {
  cat <<EOF
usage: iptv [M3U_URL]
    --channel    channel to play, with form like "[CH:100]"
    --help       Display help
EOF
}

if [[ $1 == "-c" ]] || [[ $1 == "--channel" ]]; then
  selected="$2"
fi

if [ ! -n "$selected" ]; then
  usage
  exit 1
fi

selected_channel=$(echo "$selected" | sed 's/.*\(\[CH:[0-9]\+\]\).*/\1/')
selected_channel_line=$(cat "$channels_file" | grep -F "$selected_channel")
selected_channel_url=$(echo "$selected_channel_line" | grep -oE 'url:(.*)' | sed 's/url://' | tr -d '\r')
selected_channel_name=$(echo "$selected_channel_line" | sed 's/\(.*\) url:.*/\1/')

printf "Playing %s from %s" "$selected_channel_url" "$selected_channel_name"
mpv "$selected_channel_url"
